##################################

- alias: "The Entryway Camera Detected a face"
  hide_entity: false
  trigger:
    - platform: state
      entity_id: binary_sensor.entryway_camera_person_detected
      to: 'on'
  action:
    - service: script.speech_engine
      data_template: 
        value1: 'It looks like someone is coming to visit.'
        value2: ' '
        value3: ' '
        
#- alias: "The Master bedroom Camera Detected a face"
#  hide_entity: false
#  trigger:
#    - platform: state
#      entity_id: binary_sensor.master_bedroom_camera_person_detected
#      to: 'on'
#  action:
#    - service: script.speech_engine
#      data_template: 
#        value1: 'I think I saw someone on my master bedroom camera, is Ronan awake?'
#        value2: ' '
#        value3: ' '        