###################################
## @CCOSTAN
## Original Repo : https://github.com/CCOSTAN/Home-AssistantConfig
###################################

- alias: Door Chime
  trigger:
    - platform: state
      entity_id:
        - group.entry_points

  condition:
    - condition: state
      entity_id: group.family
      state: 'home'
    - condition: time
      after: '09:30:00'
      before: '22:00:00'

  action:
    - service: media_player.turn_on
      entity_id: 
        - media_player.living_room_speaker
        - media_player.craft_room_speaker
        - media_player.master_bedroom_speaker          
        - media_player.hall_kiosk

    - service: media_player.volume_set
      entity_id:
        - media_player.living_room_speaker
        - media_player.craft_room_speaker
        - media_player.master_bedroom_speaker          
        - media_player.hall_kiosk
      data:
        volume_level: 0.40

    - service: media_player.play_media
      data_template:
        entity_id:
          - media_player.living_room_speaker
          - media_player.craft_room_speaker
          - media_player.master_bedroom_speaker          
          - media_player.hall_kiosk
        media_content_id: >
          {% if trigger.to_state.state == 'on' %}
          https://home.theneelyfamily.net:8123/local/sounds/one-tone-chime.mp3
          {% else %}
          https://home.theneelyfamily.net:8123/local/sounds/two-tone-chime.mp3
          {% endif %}
        media_content_type: audio/mp4
