##############################################################################
###  Detect when things are on and forgotten about. Like any Good Watchdog.
##############################################################################

- alias: Automated Light WatchDog!
  trigger:
    - platform: state
      entity_id:
        - group.foyer_lights
      to: 'on'
      for: '00:20:00'

    - platform: state
      entity_id:
        - switch.garage_light
      to: 'on'
      for: '00:30:00'

#Turn it off!
  action:
    - service: homeassistant.turn_off
      data_template:
        entity_id: "{{ trigger.entity_id }}"
