homeassistant:
  # Omitted values in this section will be auto detected using freegeoip.io

  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: 210
  # Name of the location where Home Assistant is running
  name: Home
  # C for Celcius, F for Fahrenheit
  temperature_unit: F
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago
  # Customization file
  customize: !include customize.yaml
  #customize_glob: !include customize_glob.yaml
  packages: !include_dir_named packages
#  whitelist_external_dirs:
#    - '/home/homeassistant/.homeassistant/downloads'

python_script:

weather:
  - platform: yweather
    name: Weather
    woeid: !secret woeid

customizer:
  custom_ui: hosted
  hide_attributes:
    - node_id
    - value_index

emulated_hue:
  host_ip: 192.168.74.14
  listen_port: 8300
#  off_maps_to_on_domains:
#    - script
#    - scene
  expose_by_default: true
  exposed_domains:
   - light  
#  expose_by_default: false

zone:
  name: Home
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  radius: 200
  icon: mdi:home

zone 2:
 name: Papaw and Nana
 latitude: !secret latitude_g_parents
 longitude: !secret longitude_g_parents
 radius: 1000
 icon: mdi:home-map-marker

zone 3:
 name: ADTRAN
 latitude: !secret latitude_adtran
 longitude: !secret longitude_adtran
 radius: 1000
 icon: mdi:city

zone 4:
 name: The Shaws
 latitude: !secret latitude_shaws
 longitude: !secret longitude_shaws
 radius: 400
 icon: mdi:home-map-marker

zone 5:
 name: Mimi and Papaw
 latitude: !secret latitude_papaw_mimi
 longitude: !secret longitude_papaw_mimi
 radius: 200
 icon: mdi:home-map-marker
 
zone 6:
 name: Gym
 latitude: !secret latitude_gym
 longitude: !secret longitude_gym
 radius: 200
 icon: mdi:home-map-marker
 
zone 7:
  name: Karate
  latitude: !secret latitude_karate
  longitude: !secret longitude_karate
  radius: 200
  icon: mdi:karate
  
panel_iframe:
  nodered_flows:
    title: 'Node-RED Flows'
    url: 'http://hassio.local:1880'
    icon: mdi:nodejs

panel_custom:
  - name: floorplan
    sidebar_title: Alarm Panel
    sidebar_icon: mdi:security-home
    url_path: floorplan
    config:
      hide_app_toolbar:
      config: /local/custom_ui/floorplan/floorplan.yaml

  - name: clock
    sidebar_title: Alarm Clock
    sidebar_icon: mdi:alarm
    url_path: clock
    config:
      hide_app_toolbar:
      config: /local/custom_ui/floorplan/floorclock.yaml

# insteon_plm supported configuration variables    
insteon_plm:
  port: /dev/ttyUSB0
  
zwave:
  usb_path: /dev/ttyACM0
light:

updater:
  include_used_components: true

abode:
  username: !secret abode_username
  password: !secret abode_password
# usps:
#   username: !secret usps_username
#   password: !secret usps_password
#Adds Alexa and Google Home support

# Enables configuration UI
config:

map:

#downloader:
#  download_dir: downloads

http:
  api_password: !secret http_password
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem  
#  ip_ban_enabled: True
#  login_attempts_threshold: 3
#  trusted_networks:
#    - 192.168.74.0/24

# Discover some devices automatically
discovery:
  ignore:
#    - apple_tv


# Allows you to issue voice commands from the frontend in enabled browsers
conversation:
ffmpeg:
camera:
  - platform: generic
    still_image_url: 'https://icons.wxug.com/data/weather-maps/radar/united-states/columbus-georgia-region-current-radar-animation.gif'
    name: WundergroundRadar
  - platform: generic
    name: worldtime
    still_image_url: https://imgs.xkcd.com/comics/now.png    


#ifttt:
#  key: !secret ifttt_key

sun:

media_player:
  # - platform: apple_tv
  #   host: 192.168.2.90
  #   login_id: !secret apple_hsgid

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_secret

device_tracker:
  - platform: owntracks    
    track_new_devices: yes  
    max_gps_accuracy: 200
#  - platform: unifi
#    host: 192.168.2.163
#    username: !secret unifi_username
#    password: !secret unifi_password
#    verify_ssl: False
  - platform: mikrotik
    host: 192.168.74.1
    username: !secret mikrotik_user
    password: !secret mikrotik_pass
  - platform: geofency
  # - platform: asuswrt
  #   host: 192.168.2.1
  #   protocol: telnet
  #   username: !secret asus_username
  #   password: !secret asus_password
  - platform: nmap_tracker
    hosts: 192.168.74.0/24
    track_new_devices: no
    exclude:
      - 192.168.74.14
      - 192.168.74.1
      - 192.168.74.3      
  #  scan_options: " --privileged -sP "
  # consider_home: 1800 - Added to known_devices.yaml instead on a device by device basis.

notify:
#  - platform: ios
  - platform: pushbullet
    api_key: !secret pushbullet_key
    name: pushbullet
  - platform: group
    name: iOS
    services:
      - service: ios_gradys_iphone
      - service: ios_kates_iphone
  - platform: group
    name: ios_abode_updates
    services:
      - service: ios_gradys_iphone
        data:
          title: 'Enable Abode updates?'
          data:
            push:
              badge: 0
              category: "abode_updates"
# Log Severities: notset, debug, info, warn, warning, error, fatal, critical
logger:
  default: info
  logs:
    homeassistant.components.image_processing: critical
    homeassistant.components.python_script: warn
    homeassistant.components.camera.synology: critical
    homeassistant.components.camera.generic: critical
    homeassistant.components.sensor.wunderground: critical
    homeassistant.components.sensor.pi_hole: critical
    homeassistant.components.media_player.plex: critical
    homeassistant.components.telegram_bot: critical
    homeassistant.components.sensor.darksky: critical
    pychromecast.socket_client: critical
    aiohttp.access: critical
    aiohttp.server: critical
    haffmpeg.core: critical
    homeassistant.helpers.entity: critical
    homeassistant.components.insteon_plm: warn
    insteonplm.protocol: warn
    homeassistant.components.zwave: warn
    homeassistant.components.http.ban: warn
    homeassistant.components.ios: debug
    homeassistant.components.notify: debug
# Text to speech
tts:
  - platform: google
#    cache: true
#    cache_dir: /home/homeassistant/.homeassistant/tts
    time_memory: 300

mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: home-assistant-1
#  username: !secret mqtt_username
#  password: !secret mqtt_password

vacuum:
  - platform: roomba
    host: 192.168.74.166
    username: 3144460001026600
    password: :1:1502753718:HmTNObX3r6oqlVay
    name: Roomba 890
    
alexa:
dialogflow:

# Includes 
intent_script: !include intent_script.yaml
ios: !include ios.yaml
alert: !include alert.yaml
automation: !include_dir_merge_list automation
group: !include groups.yaml
script: !include_dir_merge_list script
sensor: !include sensor.yaml
switch: !include switches.yaml
binary_sensor: !include binary_sensor.yaml
input_select: !include input_select.yaml
input_boolean: !include_dir_merge_list input_boolean
#input_number: !include input_number.yaml
frontend: !include frontend.yaml
recorder: !include recorder.yaml
logbook: !include logbook.yaml
#history: !include history.yaml
