homeassistant:
  # Omitted values in this section will be auto detected using freegeoip.io

  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: 210
  # Name of the location where Home Assistant is running
  name: Home
  # C for Celcius, F for Fahrenheit
  temperature_unit: F
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago
  # Customization file
  customize: !include_dir_merge_named customize
  customize_domain:
    automation:
      initial_state: 'on'
  customize_glob:
    "automation.*watchdog*":
      icon: mdi:timer
    "sensor.dark_sky_*":
      homebridge_hidden: true
    "scene.month_*_colors":
      hidden: true
      emulated_hue_hidden: true
      homebridge_hidden: true  

  packages: !include_dir_named packages
#  whitelist_external_dirs:
#    - '/home/homeassistant/.homeassistant/downloads'

#python_script:

weather:
  - platform: yweather
    name: Weather
    woeid: !secret woeid

customizer:
  custom_ui: hosted
  hide_attributes:
    - node_id
    - value_index

emulated_hue:
  host_ip: 192.168.74.14
  listen_port: 8300
#  off_maps_to_on_domains:
#    - script
#    - scene
  expose_by_default: true
#  exposed_domains:
#   - light 
#   - switch 
#  expose_by_default: false

#panel_iframe:
#  nodered_flows:
#    title: 'Node-RED Flows'
#    url: 'http://hassio.local:1880'
#    icon: mdi:nodejs

panel_custom:
  - name: floorplan
    sidebar_title: House Panel
    sidebar_icon: mdi:security-home
    url_path: floorplan
    config:
      hide_app_toolbar:
      config: /local/custom_ui/floorplan/floorplan.yaml

  - name: clock
    sidebar_title: Alarm Clock
    sidebar_icon: mdi:alarm
    url_path: clock
    config:
      hide_app_toolbar:
      config: /local/custom_ui/floorplan/floorclock.yaml

# insteon_plm supported configuration variables    
insteon_plm:
  port: /dev/ttyUSB0
  
zwave:
  usb_path: /dev/ttyACM0
light:

updater:
  include_used_components: true

abode:
  username: !secret abode_username
  password: !secret abode_password
# usps:
#   username: !secret usps_username
#   password: !secret usps_password
#Adds Alexa and Google Home support

# Enables configuration UI
config:

map:

#downloader:
#  download_dir: downloads

http:
  api_password: !secret http_password
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem  
  base_url: home.theneelyfamily.net:8123
#  ip_ban_enabled: True
#  login_attempts_threshold: 3
#  trusted_networks:
#    - 192.168.74.0/24

# Discover some devices automatically
discovery:
  ignore:
#    - apple_tv


# Allows you to issue voice commands from the frontend in enabled browsers
conversation:
ffmpeg:
camera:
  - platform: generic
    still_image_url: 'https://icons.wxug.com/data/weather-maps/radar/united-states/columbus-georgia-region-current-radar-animation.gif'
    name: WundergroundRadar
  - platform: generic
    name: worldtime
    still_image_url: https://imgs.xkcd.com/comics/now.png    


ifttt:
  key: !secret ifttt_key

sun:

media_player:
  # - platform: apple_tv
  #   host: 192.168.2.90
  #   login_id: !secret apple_hsgid
  - host: 192.168.74.23
    login_id: 00000000-4356-1ee4-b790-28fd4d974dda
    name: Bedroom Apple TV
    start_off: true
    credentials: C7CBFA5A22B4145B:4C83B51284E4C1965C96F0E2592C87E4DB1FB673C758D9639EE33B580FC86F95
  - host: 192.168.74.38
    login_id: 00000000-075e-a453-ffa9-28d44d414e34
    name: Boys Room Apple TV
    start_off: true
  - host: 192.168.74.81
    login_id: 00000000-075e-a453-ffa9-28d44d414e34
    name: Living Room Apple TV
    start_off: true
  - host: 192.168.74.119
    login_id: 00000000-075e-a453-ffa9-28d44d414e34
    name: Fiona's Apple TV
    start_off: true

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_secret

notify:
#  - platform: ios
  - platform: pushbullet
    api_key: !secret pushbullet_key
    name: pushbullet
  - platform: group
    name: iOS
    services:
      - service: ios_gradys_iphone
      - service: ios_kates_iphone
  - platform: group
    name: ios_abode_updates
    services:
      - service: ios_gradys_iphone
        data:
          title: 'Enable Abode updates?'
          data:
            push:
              badge: 0
              category: "abode_updates"
# Log Severities: notset, debug, info, warn, warning, error, fatal, critical
logger:
  default: info
  logs:
    homeassistant.components.image_processing: critical
    homeassistant.components.python_script: warn
    homeassistant.components.camera.synology: critical
    homeassistant.components.camera.generic: critical
    homeassistant.components.sensor.wunderground: critical
    homeassistant.components.sensor.pi_hole: critical
    homeassistant.components.media_player.plex: critical
    homeassistant.components.telegram_bot: critical
    homeassistant.components.sensor.darksky: critical
    pychromecast.socket_client: critical
    aiohttp.access: critical
    aiohttp.server: critical
    haffmpeg.core: critical
    homeassistant.helpers.entity: critical
    homeassistant.components.insteon_plm: warn
    insteonplm.protocol: warn
    homeassistant.components.zwave: warn
    homeassistant.components.http.ban: warn
    homeassistant.components.ios: warn
    homeassistant.components.notify: warn
# Text to speech
tts:
  - platform: google
#    cache: true
#    cache_dir: /home/homeassistant/.homeassistant/tts
    time_memory: 300

  - platform: amazon_polly
    aws_access_key_id: !secret aws_access_key_ID
    aws_secret_access_key: !secret aws_secret_access_key
    region_name: 'us-east-1'
    text_type: ssml
    cache: True
    cache_dir: /data/tts
mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: home-assistant-1
#  username: !secret mqtt_username
#  password: !secret mqtt_password

vacuum:
  - platform: roomba
    host: 192.168.74.166
    username: 3144460001026600
    password: :1:1502753718:HmTNObX3r6oqlVay
    name: Roomba 890
    
alexa:
dialogflow:

# Includes 
intent_script: !include intent_script.yaml
ios: !include ios.yaml
alert: !include alert.yaml
automation: !include_dir_merge_list automation
device_tracker: !include_dir_merge_list device_tracker
group: !include_dir_merge_named group
zone: !include_dir_merge_list zones
scene: !include_dir_merge_list scene
switch: !include_dir_merge_list switch
script: !include_dir_merge_named script
sensor: !include_dir_merge_list sensor
binary_sensor: !include_dir_merge_list binary_sensor
input_select: !include input_select.yaml
input_boolean: !include_dir_merge_named input_boolean
input_number: !include input_number.yaml
frontend: !include frontend.yaml
recorder: !include recorder.yaml
logbook: !include logbook.yaml
#history: !include history.yaml
