#-------------------------------------------
# @CCOSTAN
# Original Repo : https://github.com/CCOSTAN/Home-AssistantConfig
#-------------------------------------------
homeassistant:
  customize:
    input_boolean.self_destruct:
      friendly_name: 'Self Destruct'
      icon: mdi:skull
      emulated_hue_hidden: False
      hidden: False
#-------------------------------------------
input_boolean:
  self_destruct:
    name: Self Destruct
    initial: off

#-------------------------------------------
##############################################################################
###  Pretend to blow up the house..
##############################################################################

automation:
  - alias: 'Self Destruct sequence'
    trigger:
      - platform: state
        entity_id: input_boolean.self_destruct
        to: 'on'

    action:
    - service: media_player.turn_on
      entity_id: media_player.living_room_speaker

    - service: media_player.volume_set
      entity_id:
        - media_player.living_room_speaker
      data:
        volume_level: 0.22

    - service: media_player.play_media
      entity_id:
          - media_player.living_room_speaker
          - media_player.craft_room_speaker
          - media_player.master_bedroom_speaker
          - media_player.entry_alarm_panel
          - media_player.hall_kiosk
      data_template:
        media_content_id: >
          "https://home.theneelyfamily.net:8123/local/sounds/speechcons/self_destruct.mp3"
        media_content_type: audio/mp4
    - service: light.turn_on
      entity_id:
        - group.all_lights
      data:
        flash: long
    - service: switch.turn_off
      entity_id:
        - group.all_switches
    - service: light.turn_off
      entity_id:
        - group.all_lights
    - service: input_boolean.turn_off
      entity_id:
        - input_boolean.self_destruct
