######################################################################
##  Garage Status Announcements
######################################################################
- alias: 'Door Opened'

  trigger:
    - platform: state
      entity_id:
        - binary_sensor.back_door # back door #
        - binary_sensor.front_door # front door
        - binary_sensor.garage_door # Interior Garage Door #
        - binary_sensor.office_door # Office Door #
        - binary_sensor.den_door # Den Door #
      to: 'Open'
      for:
        minutes: 2

  action:
    - service: script.notify_engine
      who: 'family'
      data_template:
        value1: "The {{ trigger.to_state.attributes.friendly_name }} has been {{ (trigger.to_state.state)|replace('_', ' ') }}."
        value2: ''
        value3: ''

#    - wait_template: "{{ states.media_player.living_room_speaker.state != 'playing' }}"
#      timeout: 00:01:30

    - service: input_boolean.turn_on
      entity_id: input_boolean.alert_mode

    - service: script.speech_engine
      data_template:
        call_window_check: 1
        call_inside_weather: 1
