###################################
## Garadget Stuff -  [Garadget](http://amzn.to/2jQLpVQ) - Garage Door opener/sensor
###################################

- alias: 'Wind Speed Garage Door Check'
  hide_entity: True
  trigger:
    - platform: numeric_state
      entity_id: sensor.dark_sky_wind_speed
      above: 20

  condition:
    - condition: template
      value_template: "{{ states('cover.garage_door_opener') == 'open' }}"

  action:
    - service: script.notify_engine
      data_template:
        value1: 'Check Garage Doors:'
        value2: "Small: {{ states('cover.garage_door_opener')}}"

    - service: input_boolean.turn_on
      entity_id: input_boolean.alert_mode

    - service: script.speech_engine
      data_template:
        value1: >
          "The winds are picking up outside.  The wind speed is {{ states('sensor.dark_sky_wind_speed')|round}} miles per hour.  For safety, please close the garage doors.
          {% if is_state('cover.garage_door_opener', 'open') -%}
            The Garage Door is open
          {% endif -%}
