###################################
## Tornados are no Joke.
###################################

- alias: 'High Wind Speed Notification'
  hide_entity: True
  trigger:
    - platform: numeric_state
      entity_id: sensor.dark_sky_wind_speed
      above: 50

  action:
    - service: script.notify_engine
      data_template:
        value1: 'VERY HIGH WINDS:'
        value2: "{{ states('sensor.dark_sky_wind_speed')}}"
        value3: ' '

    - service: input_boolean.turn_on
      entity_id: input_boolean.alert_mode

    - service: script.speech_engine
      data_template:
        value1: >
          "ATTENTION: The wind speed is now {{ states('sensor.dark_sky_wind_speed')|round}} miles per hour.  Please make sure everyone is inside for safety."
        call_window_check: 1
        call_garage_check: 1

    - service: script.emergency


- alias: 'Turn outside lights on when cloudy'
  hide_entity: true
  trigger:
    - platform: numeric_state
      entity_id: sensor.dark_sky_cloud_coverage
      above: 85

  action:
    - service: script.notify_engine
      data_template:
        value1: 'Its getting very cloudy outside.  I will turn on the outside lighting.'
        value2: ' '
        value3: ' '

    - service: script.speech_engine
      data_template:
        value1: 'Its getting very cloudy outside.  I will turn on the outside lighting.'
        value2: ' '
        value3: ' '

    - service: switch.turn_on
      entity_id:
        - group.exterior_lights
      