###################################
## Tornados are no Joke.
###################################

- alias: 'High Wind Speed Notification'
  hide_entity: True
  trigger:
    - platform: numeric_state
      entity_id: sensor.dark_sky_wind_speed
      above: 50

  action:
    - service: script.notify_engine
      data_template:
        value1: 'VERY HIGH WINDS:'
        value2: "{{ states('sensor.dark_sky_wind_speed')}}"
        value3: ' '

    - service: input_boolean.turn_on
      entity_id: input_boolean.alert_mode

    - service: script.speech_engine
      data_template:
        value1: >
          "ATTENTION: The wind speed is now {{ states('sensor.dark_sky_wind_speed')|round}} miles per hour.  Please make sure everyone is inside for safety."
        call_window_check: 1
        call_garage_check: 1

    - service: script.emergency

#############

- alias: "Minutely Summary Change"
  hide_entity: false
  trigger:
    - platform: state
      entity_id:
        - sensor.dark_sky_minutely_summary
  action:
    - service: script.speech_engine
      data_template:
        value1: "{{ states('sensor.dark_sky_wind_speed')}}"
        value2: ' '
        value3: ' '
        

- alias: 'Turn outside lights on when cloudy'
  hide_entity: false
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sun.sun
        state: 'above_horizon'
      - condition: state
        entity_id: group.exterior_lights
        state: 'off'  
  trigger:
    - platform: numeric_state
      entity_id: sensor.dark_sky_cloud_coverage
      above: 85

  action:
    - service: script.notify_engine
      data_template:
        value1: 'Its getting very cloudy outside.  I will turn on the outside lighting.'
        value2: ' '
        value3: ' '

    - service: script.speech_engine
      data_template:
        value1: 'Its getting very cloudy outside.  I will turn on the outside lighting.'
        value2: ' '
        value3: ' '

    - service: switch.turn_on
      entity_id:
        - group.exterior_lights
      
- alias: 'Turn outside lights off when clearing'
  hide_entity: false
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sun.sun
        state: 'above_horizon'
      - condition: state
        entity_id: group.exterior_lights
        state: 'on'  
  trigger:
    - platform: numeric_state
      entity_id: sensor.dark_sky_cloud_coverage
      below: 80

  action:
    - service: script.notify_engine
      data_template:
        value1: 'The sky seems to be clearing up.  I will turn off the outside lighting now.'
        value2: ' '
        value3: ' '

    - service: script.speech_engine
      data_template:
        value1: 'The sky seems to be clearing up.  I will turn off the outside lighting now.'
        value2: ' '
        value3: ' '

    - service: switch.turn_on
      entity_id:
        - group.exterior_lights      