Home Security:
  control: hidden
  entities:
    - alarm_control_panel.abode_alarm
    - cover.garage_door_opener
    - binary_sensor.back_door
    - binary_sensor.front_door
    - binary_sensor.garage_door
    - binary_sensor.den_door
    - binary_sensor.office_door
    - sensor.overflow_pantry_door