- platform: 'bayesian'
  prior: 0.8
  name: 'Kate Home'
  probability_threshold: 0.92
  observations:
    - entity_id: 'device_tracker.katesiphone4'
      prob_given_true: 0.8
      prob_given_false: 0.2
      platform: 'state'
      to_state: 'home'
    - entity_id: 'device_tracker.kates_iphone'
      prob_given_true: 0.99
      prob_given_false: 0.01
      platform: 'state'
      to_state: 'home'
- platform: 'bayesian'
  prior: 0.75
  name: 'Grady Home'
  probability_threshold: 0.92
  observations:
    - entity_id: 'device_tracker.grady_ot_iphone'
      prob_given_true: 0.8
      prob_given_false: 0.2
      platform: 'state'
      to_state: 'home'
    - entity_id: 'device_tracker.gradysiphone'
      prob_given_true: 0.99
      prob_given_false: 0.01
      platform: 'state'
      to_state: 'home'
    - entity_id: 'device_tracker.gradys_iphone'
      prob_given_true: 0.99
      prob_given_false: 0.01
      platform: 'state'
      to_state: 'home'
#- platform: 'bayesian'
#  prior: 0.8
#  name: 'Conor Home'
#  probability_threshold: 0.92
#  observations:
#    - entity_id: 'device_tracker.conorsiphone3'
#      prob_given_true: 0.8
#      prob_given_false: 0.2
#      platform: 'state'
#      to_state: 'home'
#- platform: 'bayesian'
#  prior: 0.8
#  name: 'Hunter Home'
#  probability_threshold: 0.92
#  observations:
#    - entity_id: 'device_tracker.huntersone6plus'
#      prob_given_true: 0.8
#      prob_given_false: 0.2
#      platform: 'state'
#      to_state: 'home'
#- platform: 'bayesian'
#  prior: 0.8
#  name: 'Fiona Home'
#  probability_threshold: 0.92
#  observations:
#    - entity_id: 'device_tracker.fisiphone'
#      prob_given_true: 0.8
#      prob_given_false: 0.2
#      platform: 'state'
#      to_state: 'home'
#- platform: ping
#  host: 192.168.74.1
#  name: PiHole