- platform: template
  sensors:
    overflow_pantry_door:
      friendly_name: "Overflow Pantry Door"
      value_template: '{% if is_state("sensor.vision_zd2102_eu_doorwindow_sensor_access_control", "22") %}Open{% else %}Closed{% endif %}'
      icon_template: '{% if is_state("sensor.vision_zd2102_eu_doorwindow_sensor_access_control", "22") %}mdi:door-open{% else %}mdi:door{% endif %}'
