- platform: template
  sensors:
    overflow_pantry_door:
      friendly_name: "Overflow Pantry Door"
      value_template: '{% if is_state("sensor.overflow_pantry_door_access_control", "22") %}open{% else %}closed{% endif %}'
      icon_template: '{% if is_state("sensor.overflow_pantry_door_access_control", "22") %}mdi:door-open{% else %}mdi:door{% endif %}'
