###################################################
## Various MQTT sensors
###################################################

#- platform: mqtt
#  state_topic: "ifttt/rachio/watering_time"
#  name: "Rachio_watering_time"
#
#- platform: mqtt
#  state_topic: "dash/medicine/medicine_time"
#  name: "Medicine time"
#

- platform: mqtt
  state_topic: "owntracks/pi/katephone/step"
  name: "Steps Kate"
  value_template: '{{ value_json.steps }}'
- platform: mqtt
  state_topic: "owntracks/pi/gradyphone/step"
  name: "Steps Grady"
  value_template: '{{ value_json.steps }}'
