- platform: template
  sensors:
    climate_foh_temperature:
      friendly_name: 'Target Temperature'
      unit_of_measurement: '°F'
      value_template: >-
        {% if is_state('input_select.hvac_operation_mode_downstairs', 'Heat') %}
            {{ states.climate.foh_heating_1.attributes.temperature }}
        {% elif is_state('input_select.hvac_operation_mode_downstairs', 'Cool') %}
            {{ states.climate.foh_cooling_1.attributes.temperature }}
        {% else %}
            OFF
        {% endif %}
 
    climate_boh_temperature:
      friendly_name: 'Target Temperature'
      unit_of_measurement: '°F'
      value_template: >-
        {% if is_state('input_select.hvac_operation_mode_upstairs', 'Heat') %}
            {{ states.climate.boh_heating_1.attributes.temperature }}
        {% elif is_state('input_select.hvac_operation_mode_upstairs', 'Cool') %}
            {{ states.climate.boh_cooling_1.attributes.temperature }}
        {% else %}
            OFF
        {% endif %}   
