#####
### Sets the foh thermostat temperature when the hvac_target_temp input_slider is changed
#####
- alias: 'Set front of the house thermostat temperature based on input_slider'
  trigger:
    - platform: state
      entity_id: input_slider.hvac_target_temp_foh
  action:
    - service: climate.set_temperature
      data_template:
        entity_id: >-
          {% if is_state('input_select.hvac_operation_mode_foh', 'Heat') %}
              climate.2gig_technologies_ct100_thermostat_usa_heating_1_2
          {% elif is_state('input_select.hvac_operation_mode_foh', 'Cool') %}
              climate.2gig_technologies_ct100_thermostat_usa_cooling_1_2
          {% endif %}
        temperature: "{{ states('input_slider.hvac_target_temp_foh') }}"

#####
### Sets the hvac_target_temp input_slider when the foh thermostat temperature is manually changed
#####
#- alias: 'Set input_slider based on foh thermostat temperature'
#  trigger:
#    platform: state
#    entity_id: climate.thermostat_foh_cooling_1_31_2
#  condition:
#    condition: template
#    value_template: '{{ trigger.to_state.attributes.temperature != trigger.from_state.attributes.temperature }}'
#  action:
#    service: input_slider.select_value
#    entity_id: input_slider.hvac_target_temp_foh
#    value_template:
#      entity_id: >-
#        {% if is_state('input_select.hvac_operation_mode_foh', 'Heat') %}
#            '{{ states.climate.thermostat_foh_heating_1_31_1.attributes.temperature }}'
#        {% elif is_state('input_select.hvac_operation_mode_foh', 'Cool') %}
#            '{{ states.climate.thermostat_foh_cooling_1_31_2.attributes.temperature }}'
#        {% endif %}
