################################################################
## Package / Homebridge
################################################################

################################################
## Customize
################################################

homeassistant:
  customize_domain:
    alarm_control_panel:
      homebridge_hidden: false

    automation:
      homebridge_hidden: true

    binary_sensor:
      homebridge_hidden: true

    climate:
      homebridge_hidden: true

    cover:
      homebridge_hidden: false

    device_tracker:
      homebridge_hidden: true

    fan:
      homebridge_hidden: true

    group:
      homebridge_hidden: true

    input_boolean:
      homebridge_hidden: true

    light:
      homebridge_hidden: false

    lock:
      homebridge_hidden: false

    media_player:
      homebridge_hidden: true

    script:
      homebridge_hidden: true

    scene:
      homebridge_hidden: true

    remote:
      homebridge_hidden: true

    sensor:
      homebridge_hidden: true

    switch:
      homebridge_hidden: false

    switch.auto_away:
      homebridge_hidden: true

    switch.auto_home:
      homebridge_hidden: true

    switch.flash_lights_when_alarmin:
      homebridge_hidden: true

    switch.good_morning:
      homebridge_hidden: true

    switch.good_night:
      homebridge_hidden: true
