#-------------------------------------------
#  Network Related Packages
# @CCOSTAN
# Original Repo : https://github.com/CCOSTAN/Home-AssistantConfig
#-------------------------------------------

#-------------------------------------------
sensor:
  - platform: template
    sensors:
#        wii:
#          friendly_name: 'Wii'
#          value_template: "{{ 'Online' if is_state('device_tracker.wii', 'home') else 'Offline' }}"

        nintendo_3ds:
          friendly_name: 'Conor''s 3DS'
          value_template: "{{ 'Online' if is_state('device_tracker.nintendo_3ds', 'home') else 'Offline' }}"

        nintendo_3ds_2:
          friendly_name: 'Fiona''s 3DS'
          value_template: "{{ 'Online' if is_state('device_tracker.nintendo_3ds_2', 'home') else 'Offline' }}"

        den_ps4:
          friendly_name: 'Den PS4'
          value_template: "{{ 'Online' if is_state('device_tracker.0cfe45f974ec', 'home') else 'Offline' }}"

        b4_ps4:
          friendly_name: 'MBR PS4'
          value_template: "{{ 'Online' if is_state('device_tracker.nintendo_3ds_2', 'home') else 'Offline' }}"

        den_ap:
          friendly_name: 'Unifi Den AP'
          value_template: "{{ 'Online' if is_state('device_tracker.denap', 'home') else 'Offline' }}"

        dining_ap:
          friendly_name: 'Unifi Dining Room AP'
          value_template: "{{ 'Online' if is_state('device_tracker.diningroom', 'home') else 'Offline' }}"

        master_ap:
          friendly_name: 'Unifi Master Bedroom AP'
          value_template: "{{ 'Online' if is_state('device_tracker.masterbedroom', 'home') else 'Offline' }}"

        amazon_fire_7:
          friendly_name: 'Amazon Fire 7 HD Tablet'
          value_template: "{{ 'Online' if is_state('device_tracker.amazon9445cb18d', 'home') else 'Offline' }}"

        amazon_dot_1:
          friendly_name: 'Master Bedroom Amazon Dot'
          value_template: "{{ 'Online' if is_state('device_tracker.amazon_dot', 'home') else 'Offline' }}"

        amazon_dot_2:
          friendly_name: 'Craft Room Amazon Dot'
          value_template: "{{ 'Online' if is_state('device_tracker.amazon_dot', 'home') else 'Offline' }}"

        amazon_dot_3:
          friendly_name: 'Living Room Amazon Dot'
          value_template: "{{ 'Online' if is_state('device_tracker.amazon_dot', 'home') else 'Offline' }}"

        printer:
          friendly_name: 'Printer'
          value_template: "{{ 'Online' if is_state('device_tracker.hp6ecc69', 'home') else 'Offline' }}"

        circle:
          friendly_name: 'Disney Circle'
          value_template: "{{ 'Online' if is_state('device_tracker.circle', 'home') else 'Offline' }}"

        nest_entryway_cam:
          friendly_name: 'Entryway Nest Cam'
          value_template: "{{ 'Online' if is_state('device_tracker.nest_downstairs', 'home') else 'Offline' }}"

        nest_master_cam:
          friendly_name: 'Master Bedroom Nest Cam'
          value_template: "{{ 'Online' if is_state('device_tracker.nest_upstairs', 'home') else 'Offline' }}"

        roomba:
          friendly_name: 'Roomba 890'
          value_template: "{{ 'Online' if is_state('device_tracker.roomba3144460001026600', 'home') else 'Offline' }}"

        vizio_tv:
          friendly_name: 'Vizio Master Bedroom TV'
          value_template: "{{ 'Online' if is_state('device_tracker.a48d3b0b8264', 'home') else 'Offline' }}"

        bedroom_atv:
          friendly_name: 'Master Bedroom Apple TV'
          value_template: "{{ 'Online' if is_state('device_tracker.bedroom', 'home') else 'Offline' }}"

        den_atv:
          friendly_name: 'Den Apple TV'
          value_template: "{{ 'Online' if is_state('device_tracker.livingrmappletv', 'home') else 'Offline' }}"

        fionas_atv:
          friendly_name: 'Fiona''s Apple TV'
          value_template: "{{ 'Online' if is_state('device_tracker.fionasappletv', 'home') else 'Offline' }}"

        boys_atv:
          friendly_name: 'Boy''s Room Apple TV'
          value_template: "{{ 'Online' if is_state('device_tracker.boysrooappletv2', 'home') else 'Offline' }}"

        rb260gsp:
          friendly_name: 'RB260 GSP'
          value_template: "{{ 'Online' if is_state('device_tracker.rb260gsp', 'home') else 'Offline' }}"

        conor:
          friendly_name: 'Conor'
          value_template: "{{ 'Home' if is_state('binary_sensor.conor', 'on') else states('device_tracker.conorsiphone')|replace('_', ' ') }}"

        finn:
          friendly_name: 'Finn'
          value_template: "{{ 'Home' if is_state('binary_sensor.finn', 'on') else states('device_tracker.finnegansipad')|replace('_', ' ') }}"

        fiona:
          friendly_name: 'Fiona'
          value_template: "{{ 'Home' if is_state('binary_sensor.fiona', 'on') else states('device_tracker.fisiphone')|replace('_', ' ') }}"

        grady:
          friendly_name: 'Grady'
          value_template: "{{ 'Home' if is_state('binary_sensor.grady', 'on') else states('device_tracker.gradys_iphone')|replace('_', ' ') }}"

        hunter:
          friendly_name: 'Hunter'
          value_template: "{{ 'Home' if is_state('binary_sensor.hunter', 'on') else states('device_tracker.huntersiphone6plus')|replace('_', ' ') }}"

        deaglan:
          friendly_name: 'Deaglan'
          value_template: "{{ 'Home' if is_state('binary_sensor.deaglan', 'on') else states('device_tracker.kateneelysipad')|replace('_', ' ') }}"
          
        kate:
          friendly_name: 'Kate'
          value_template: "{{ 'Home' if is_state('binary_sensor.kate', 'on') else states('device_tracker.katesiphone')|replace('_', ' ') }}"        

#-------------------------------------------

group:
  games:
    name: Games
    entities:
      - sensor.nintendo_3ds
      - sensor.nintendo_3ds_2
      - sensor.den_ps4
  ios:
    name: iOS Devices
    entities:
      - sensor.conors_iphone
      - sensor.finnegans_ipad
      - sensor.fionas_iphone
      - sensor.gradys_iphone
      - sensor.hunters_iphone
      - sensor.deaglans_ipad
      - sensor.kates_iphone
  network:
    name: Network Stuff
    entities:
      - sensor.den_ap    
      - sensor.dining_ap    
      - sensor.master_ap
      - sensor.printer
      - sensor.rb260gsp
  home:
    name: Home Stuff
    entities:
      - sensor.circle    
      - sensor.amazon_fire_7
      - sensor.amazon_dot_1
      - sensor.amazon_dot_2
      - sensor.amazon_dot_3
      - sensor.printer

#-------------------------------------------------------------------------------------
automation:
  - alias: 'Device Status'
    hide_entity: True
    trigger:
         - platform: state
           entity_id:
             - sensor.wii
             - sensor.Hue_Hub_1
             - sensor.Hue_Hub_2
             - sensor.tablotv
             - sensor.alexa_echo
             - sensor.amazon_dot
             - sensor.circle
             - sensor.rachio
             - sensor.skybell
             - sensor.printer
             - sensor.chromecast_audio_1
             - sensor.chromecast_audio_2
             - sensor.nest_upstairs
             - sensor.nest_downstairs
             - sensor.study_ap
             - sensor.actiontechap
             - sensor.trendnetap
             - sensor.unifi_ap
             - sensor.small_garage
             - sensor.large_garage
             - sensor.rgb_led_garage_large
             - sensor.rgb_led_garage_small
             - sensor.rgb_led_outdoor_den
             #- sensor.withings_scale
             - sensor.smart_water_meter
             - sensor.sleep_number_bed
             - sensor.bedroom_alarm_panel
             - sensor.entry_alarm_panel
             - sensor.nodemcu1
             - sensor.nodemcu2
             - sensor.nodemcu3
             - sensor.gradypihole
           to: 'offline'
           for:
             minutes: 5

    action:
      - service: script.notify_engine
        data_template:
          value1: 'Device Status:'
          value2: "{{ trigger.to_state.attributes.friendly_name }} is "
          value3: "{{ trigger.to_state.state }}"
          who: 'grady'

      - service: script.speech_engine
        data_template:
          value1: "{{ trigger.to_state.attributes.friendly_name }} is now {{ trigger.to_state.state }}"
