#-------------------------------------------
#  Network Related Packages
# @CCOSTAN
# Original Repo : https://github.com/CCOSTAN/Home-AssistantConfig
#-------------------------------------------

#-------------------------------------------
sensor:
  - platform: template
    sensors:
#        wii:
#          friendly_name: 'Wii'
#          value_template: "{{ 'Online' if is_state('device_tracker.wii', 'home') else 'Offline' }}"

        conor_3ds:
          friendly_name: 'Conor''s 3DS'
          value_template: "{{ 'Online' if is_state('device_tracker.nintendo_3ds', 'home') else 'Offline' }}"

        fi_3ds:
          friendly_name: 'Fiona''s 3DS'
          value_template: "{{ 'Online' if is_state('device_tracker.nintendo_3ds_2', 'home') else 'Offline' }}"

        den_ap:
          friendly_name: 'Unifi Den AP'
          value_template: "{{ 'Online' if is_state('device_tracker.denap', 'home') else 'Offline' }}"

        dining_ap:
          friendly_name: 'Unifi Dining Room AP'
          value_template: "{{ 'Online' if is_state('device_tracker.diningroom', 'home') else 'Offline' }}"

        master_ap:
          friendly_name: 'Unifi Master Bedroom AP'
          value_template: "{{ 'Online' if is_state('device_tracker.masterbedroom', 'home') else 'Offline' }}"

        amazon_fire_7:
          friendly_name: 'Amazon Fire 7 HD Tablet'
          value_template: "{{ 'Online' if is_state('device_tracker.amazon9445cb18d', 'home') else 'Offline' }}"

        amazon_dot_1:
          friendly_name: 'Amazon Dot'
          value_template: "{{ 'Online' if is_state('device_tracker.amazon_dot', 'home') else 'Offline' }}"

        amazon_dot_2:
          friendly_name: 'Amazon Dot'
          value_template: "{{ 'Online' if is_state('device_tracker.amazon_dot', 'home') else 'Offline' }}"

        amazon_dot_3:
          friendly_name: 'Amazon Dot'
          value_template: "{{ 'Online' if is_state('device_tracker.amazon_dot', 'home') else 'Offline' }}"

        printer:
          friendly_name: 'Printer'
          value_template: "{{ 'Online' if is_state('device_tracker.hp6ecc69', 'home') else 'Offline' }}"

        circle:
          friendly_name: 'Disney Circle'
          value_template: "{{ 'Online' if is_state('device_tracker.circle', 'home') else 'Offline' }}"

        nest_entryway_cam:
          friendly_name: 'Entryway Nest Cam'
          value_template: "{{ 'Online' if is_state('device_tracker.nest_downstairs', 'home') else 'Offline' }}"

        nest_master_cam:
          friendly_name: 'Master Bedroom Nest Cam'
          value_template: "{{ 'Online' if is_state('device_tracker.nest_upstairs', 'home') else 'Offline' }}"

        roomba:
          friendly_name: 'Roomba 890'
          value_template: "{{ 'Online' if is_state('device_tracker.roomba3144460001026600', 'home') else 'Offline' }}"

        vizio_tv:
          friendly_name: 'Vizio Master Bedroom TV'
          value_template: "{{ 'Online' if is_state('device_tracker.a48d3b0b8264', 'home') else 'Offline' }}"


#-------------------------------------------
group:
  network:
    entities:
      - sensor.ha_installed_version
      - sensor.ha_uptime
      - sensor.since_last_boot_templated
      - sensor.disk_used_
      - sensor.speedtest_download
      - sensor.speedtest_upload
      - sensor.study_ap
      - sensor.actiontechap
      - sensor.unifi_ap
      - sensor.wii
      - sensor.hue_hub_1
      - sensor.hue_hub_2
      - binary_sensor.carlowink
      - sensor.tablotv
      - sensor.alexa_echo
      - sensor.amazon_dot
      - sensor.circle
      - sensor.rachio
      - sensor.skybell
      - sensor.samsungtv
      - sensor.chromecast_audio_1
      - sensor.chromecast_audio_2
      - sensor.amazon_fire_stick
      - sensor.nest_upstairs
      - sensor.nest_downstairs
      - sensor.large_garage
      - sensor.small_garage
      - sensor.rgb_led_garage_large
      - sensor.rgb_led_garage_small
      - sensor.rgb_led_outdoor_den
      - sensor.withings_scale
      - sensor.smart_water_meter
      - sensor.sleep_number_bed
      - sensor.printer
      - sensor.bedroom_alarm_panel
      - sensor.entry_alarm_panel
      - sensor.NodeMCU1
      - sensor.NodeMCU2
      - sensor.NodeMCU3
      - sensor.carlopihole


#-------------------------------------------------------------------------------------
automation:
  - alias: 'Device Status'
    hide_entity: True
    trigger:
         - platform: state
           entity_id:
             - sensor.wii
             - sensor.Hue_Hub_1
             - sensor.Hue_Hub_2
             - sensor.tablotv
             - sensor.alexa_echo
             - sensor.amazon_dot
             - sensor.circle
             - sensor.rachio
             - sensor.skybell
             - sensor.printer
             - sensor.chromecast_audio_1
             - sensor.chromecast_audio_2
             - sensor.nest_upstairs
             - sensor.nest_downstairs
             - sensor.study_ap
             - sensor.actiontechap
             - sensor.trendnetap
             - sensor.unifi_ap
             - sensor.small_garage
             - sensor.large_garage
             - sensor.rgb_led_garage_large
             - sensor.rgb_led_garage_small
             - sensor.rgb_led_outdoor_den
             #- sensor.withings_scale
             - sensor.smart_water_meter
             - sensor.sleep_number_bed
             - sensor.bedroom_alarm_panel
             - sensor.entry_alarm_panel
             - sensor.nodemcu1
             - sensor.nodemcu2
             - sensor.nodemcu3
             - sensor.carlopihole
           to: 'offline'
           for:
             minutes: 5

    action:
      - service: script.notify_engine
        data_template:
          value1: 'Device Status:'
          value2: "{{ trigger.to_state.attributes.friendly_name }} is "
          value3: "{{ trigger.to_state.state }}"
          who: 'carlo'

      - service: script.speech_engine
        data_template:
          value1: "{{ trigger.to_state.attributes.friendly_name }} is now {{ trigger.to_state.state }}"
