###################################
##  Sunrise and Sunset stuff
# @CCOSTAN
# Original Repo : https://github.com/CCOSTAN/Home-AssistantConfig
###################################

- alias: 'Sunset Stuff on'
  trigger:
    - platform: state
      entity_id: sun.sun
      from: 'above_horizon'
      to: 'below_horizon'

  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.outdoor_bathroom
        brightness: 35
    - delay: '00:{{ (range(1, 20)|random|int) }}:00'
    - service: script.speech_engine
      data:
        call_dark_outside: 1
    - service: script.monthly_color_scene
    - wait_template: >-
       {{ states.group.family.state == 'home' }}
    - service: switch.turn_on
      entity_id:
        - group.exterior_lights
    - service: light.turn_on
      entity_id:
       - light.ge_unknown_type5044_id3031_level
    - wait_template: >-
       {{ is_state('group.garage_doors', 'closed') }}
    - delay:
        minutes: 2
    - service: script.speech_engine
      data:
       call_garage_check: 1
       call_window_check: 1
